[build]
publish = "public"
command = "hugo --gc --minify"

[build.environment]
HUGO_VERSION = "0.150.0"
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"

# Try to specify build image (may not work on all accounts)
[context.production]
  build = { image = "noble" }

[context.deploy-preview]
  build = { image = "noble" }